# Generated by Django 6.1.1 on 2026-09-05 15:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='شناسه')),
                ('name', models.CharField(max_length=80, verbose_name='نام دسته')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConsultRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('message', models.TextField(blank=True, verbose_name='شرح پروژه')),
                ('is_handled', models.BooleanField(default=False, verbose_name='پیگیری شد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'درخواست مشاوره',
                'verbose_name_plural': 'درخواست\u200cهای مشاوره',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات')),
                ('total', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ کل')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('confirmed', 'تأیید شده'), ('shipped', 'ارسال شده'), ('canceled', 'لغو شده')], default='new', max_length=12, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='شناسه')),
                ('name_fa', models.CharField(max_length=60, verbose_name='نام فارسی')),
                ('name_en', models.CharField(max_length=60, verbose_name='نام لاتین')),
                ('texture', models.CharField(blank=True, max_length=120, verbose_name='بافت')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('image', models.ImageField(blank=True, null=True, upload_to='woods/', verbose_name='تصویر بافت')),
                ('image_url', models.CharField(blank=True, max_length=300, verbose_name='آدرس تصویر')),
            ],
            options={
                'verbose_name': 'نوع چوب',
                'verbose_name_plural': 'انواع چوب',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='شناسه')),
                ('title', models.CharField(max_length=140, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیح کوتاه')),
                ('price', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت (تومان)')),
                ('old_price', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت قبل از تخفیف')),
                ('badge', models.CharField(blank=True, max_length=30, verbose_name='برچسب')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='تصویر')),
                ('image_url', models.CharField(blank=True, max_length=300, verbose_name='آدرس تصویر')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category', verbose_name='دسته\u200cبندی')),
                ('wood', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.wood', verbose_name='نوع چوب')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد')),
                ('unit_price', models.PositiveBigIntegerField(default=0, verbose_name='قیمت واحد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'قلم سفارش',
                'verbose_name_plural': 'اقلام سفارش',
            },
        ),
    ]
